FROM node:7.1.0

ENV service=retryer
ENV appPath=/home/app

RUN useradd --user-group --create-home --shell /bin/false app

RUN mkdir -p $appPath/$service
RUN chown -R app:app $appPath/*

USER app
WORKDIR $appPath/$service
